#Function: add additional translations on SQLite statements not processed by babel
def translations(language):
    keywords = {}
    match language:
        case 'en':
            keywords['id-type'] = 'ID type'
            keywords['id'] = 'Identification'
            keywords['customer'] = 'Customer'
            keywords['phone'] = 'Contact Phone'
            keywords['email'] = 'E-mail'
            keywords['status'] = 'Status'
            keywords['customers'] = 'Customers'
            keywords['supplier'] = 'Supplier'
            keywords['suppliers'] = 'Suppliers'
            keywords['product'] = 'Product'
            keywords['price'] = 'Price'
            keywords['stock'] = 'Total stock'
            keywords['products'] = 'Products'
            keywords['order'] = 'Order'
            keywords['p-received'] = 'Products received'
            keywords['warehouse'] = 'Warehouse'
            keywords['receiver'] = 'Receiver'
            keywords['inbound'] = 'Inbound'
            keywords['outbound'] = 'Outbound'
            keywords['date'] = 'Date'
            keywords['p-sold'] = 'Products sold'
            keywords['amount'] = 'Amount'
            keywords['vendor'] = 'Vendor'
            keywords['user'] = 'User'
            keywords['users'] = 'Users'
            keywords['start'] = 'Start date'
            keywords['end'] = 'End date'
            keywords['activity'] = 'Activity'
            keywords['quantity'] = 'Quantity'
            keywords['day'] = 'Day'
            keywords['total'] = 'Total'

        case 'es':
            keywords['id-type'] = 'Tipo de ID'
            keywords['id'] = 'Identificación'
            keywords['customer'] = 'Cliente'
            keywords['phone'] = 'Teléfono'
            keywords['email'] = 'Correo'
            keywords['status'] = 'Estado'
            keywords['customers'] = 'Clientes'
            keywords['supplier'] = 'Proveedor'
            keywords['suppliers'] = 'Proveedores'
            keywords['product'] = 'Producto'
            keywords['price'] = 'Precio'
            keywords['stock'] = 'Existencias totales'
            keywords['products'] = 'Productos'
            keywords['order'] = 'Orden'
            keywords['p-received'] = 'Productos recibidos'
            keywords['warehouse'] = 'Bodega'
            keywords['receiver'] = 'Recibió'
            keywords['inbound'] = 'Entradas'
            keywords['outbound'] = 'Salidas'
            keywords['date'] = 'Fecha'
            keywords['p-sold'] = 'Productos vendidos'
            keywords['amount'] = 'Monto'
            keywords['vendor'] = 'Vendedor'
            keywords['user'] = 'Usuario'
            keywords['users'] = 'Usuarios'
            keywords['start'] = 'Activo desde'
            keywords['end'] = 'Activo hasta'
            keywords['activity'] = 'Actividad'
            keywords['quantity'] = 'Cantidad'
            keywords['day'] = 'Día'
            keywords['total'] = 'Total'

    return keywords

